name: build-and-test-s3-api-ubuntu

on:
  workflow_call:
    inputs:
      docker_image:
        description: The docker image and tag identifying the OS used to compile the S3 API (e.g. ubuntu:24.04).
        required: true
        type: string
      irods_package_version:
        description: The package version of iRODS used to compile the S3 API (e.g. 5.0.2-0~noble).
        required: true
        type: string
      build_artifact_suffix:
        description: The name used to uniquely identify build output across workflow jobs (e.g. ubuntu_24-5.0.2-0).
        required: true
        type: string
      client_package_directory:
        description: The directory name which is expected to hold the S3 API packages (e.g. Ubuntu_24). Required by the irods_python_ci_utilities module.
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build_s3_api:
    name: Build - ${{ inputs.irods_package_version }}, ${{ inputs.docker_image }}

    runs-on: ubuntu-latest
    container: ${{ inputs.docker_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install prerequisite packages
        run: |
          apt-get update -qq
          apt-get install -qq \
            build-essential \
            cmake \
            git \
            gnupg \
            lsb-release \
            python3-distro \
            python3-packaging \
            python3-pip \
            python3-setuptools \
            wget

      - name: Set up iRODS externals package repository
        run: |
          mkdir -p /etc/apt/keyrings
          wget -qO - https://packages.irods.org/irods-signing-key.asc | \
            gpg \
              --no-options \
              --no-default-keyring \
              --no-auto-check-trustdb \
              --homedir /dev/null \
              --no-keyring \
              --import-options import-export \
              --output /etc/apt/keyrings/renci-irods-archive-keyring.pgp \
              --import
          echo "deb [signed-by=/etc/apt/keyrings/renci-irods-archive-keyring.pgp arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | \
            tee /etc/apt/sources.list.d/renci-irods.list

      - name: Install iRODS development packages
        run: |
          apt-get update -qq
          apt-get install -qq \
            irods-dev=${{ inputs.irods_package_version }} \
            irods-runtime=${{ inputs.irods_package_version }}

      - name: Build and package
        run: |
          mkdir -p _build
          cd _build
          cmake -DIRODS_BUILD_WITH_WERROR=NO /s3_api_source
          make -j package
          cd -

      - name: List contents of build directory
        run: ls -l _build

      - name: Upload build output for dependent jobs
        uses: actions/upload-artifact@v6
        with:
          name: build_output-${{ inputs.build_artifact_suffix }}
          path: _build/*.deb
          retention-days: 1
          overwrite: true

  run_tests:
    needs: build_s3_api

    name: Test - ${{ inputs.irods_package_version }}, ubuntu-22.04, postgres-16

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download build output
        uses: actions/download-artifact@v7
        with:
          name: build_output-${{ inputs.build_artifact_suffix }}
          path: ${{ inputs.client_package_directory }}

      - name: Set up docker compose
        uses: docker/setup-compose-action@v1

      - name: Run tests
        run: |
          cp ${{ inputs.client_package_directory }}/*.deb .
          cd tests/docker
          docker compose run --rm test-runner
